Add RequestCookies class to handle HTTP cookies
yiisoft/request-provider pull request #11
Opened 2024-10-26 14:52 UTC by hacan359

- Created the RequestCookies class to manage cookies.
- It gets cookies from a RequestProviderInterface.
- Added methods to retrieve a cookie by name and check if a cookie exists.

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

2024-10-26 16:42 UTC, vjik requested changes

2024-10-26 16:42 UTC, vjik commented on CHANGELOG.md
> +- Add `Yiisoft/RequestProvider/RequestCookies` request cookie collection object (@hacan359)
```suggestion
- Add `RequestCookies` class that provides convenient access to request cookies (@hacan359)
```

2024-10-26 16:42 UTC, vjik commented on tests/RequestCookiesTest.php
> +        $requestCoockies = $this->getRequestCookies();
```suggestion
        $requestCookies = $this->getRequestCookies();
```

2024-10-26 16:42 UTC, vjik commented on tests/RequestCookiesTest.php
> +    public function testRequestCookiesGet(): void
```suggestion
    public function testGet(): void
```

2024-10-26 16:42 UTC, vjik commented on tests/RequestCookiesTest.php
> +    public function testRequestCookiesHas(): void
```suggestion
    public function testHas(): void
```

2024-10-26 16:42 UTC, vjik commented on tests/RequestCookiesTest.php
> +        $requestCoockies = $this->getRequestCookies();
```suggestion
        $requestCookies = $this->getRequestCookies();
```

2024-10-26 16:42 UTC, vjik commented on tests/RequestCookiesTest.php
> +        $container = $this->createContainer();
Here we test `RequestCookies` only, so we can don't use container and create `RequestProvider` directly.

2024-10-26 21:45 UTC, samdark commented
Thanks for the pull request. I wonder what is the benefit compared to current master:

```php
public function actionX(RequestProviderInterface $requestProvider)
{
    $cookies = $requestProvider->get()->getCookieParams();
	if (!empty($cookies['x'])) {
        $x = $cookies['x'];
        // ...
    }
}
```

To me, new code looks quite similar:

```php
public function actionX(RequestCookies $requestCookies)
{
    $cookies = $requestProvider->get()->getCookieParams();
	if ($requestCookies->has('x')) {
        $x = $requestCookies->get('x');
        // ...
    }
}
```

2024-10-27 04:42 UTC, vjik commented
> To me, new code looks quite similar:

New code is simpler and semantically more beautiful.

2024-10-27 09:21 UTC, samdark approved these changes

2024-10-27 09:21 UTC, samdark commented on README.md
> +You can work with cookie request from any place in you project. Add in config you app in middleware block
```suggestion
You can work with cookies like the following:
```

2024-10-27 09:21 UTC, samdark commented on README.md
> +class MyClass {
```suggestion
class MyClass
{
```

2024-10-27 09:21 UTC, samdark commented on README.md
> +  public function go(): void {
```suggestion
  public function go(): void
  {
```

2024-10-27 09:21 UTC, samdark commented on src/RequestCookies.php
> +        return isset($this->cookies[$name]);
```suggestion
        return array_key_exists($name, $this->cookies);
```

2024-10-27 10:39 UTC, hacan359 commented on CHANGELOG.md
> +- Add `Yiisoft/RequestProvider/RequestCookies` request cookie collection object (@hacan359)
done

2024-10-27 10:39 UTC, hacan359 commented on tests/RequestCookiesTest.php
> +        $requestCoockies = $this->getRequestCookies();
done

2024-10-27 10:40 UTC, hacan359 commented on tests/RequestCookiesTest.php
> +    public function testRequestCookiesGet(): void
done

2024-10-27 10:40 UTC, hacan359 commented on tests/RequestCookiesTest.php
> +    public function testRequestCookiesHas(): void
done

2024-10-27 10:40 UTC, hacan359 commented on tests/RequestCookiesTest.php
> +        $requestCoockies = $this->getRequestCookies();
done

2024-10-27 10:40 UTC, hacan359 commented on README.md
> +You can work with cookie request from any place in you project. Add in config you app in middleware block
done

2024-10-27 10:40 UTC, hacan359 commented on README.md
> +class MyClass {
done

2024-10-27 10:40 UTC, hacan359 commented on README.md
> +  public function go(): void {
done

2024-10-27 10:40 UTC, hacan359 commented on src/RequestCookies.php
> +        return isset($this->cookies[$name]);
done

2024-10-27 10:58 UTC, samdark commented on CHANGELOG.md
> +- Add `RequestCookies` class that provides convenient access to request cookies (@hacan359)
```suggestion
- New #11: Add `RequestCookies` class that provides convenient access to request cookies (@hacan359)
```

2024-10-27 14:34 UTC, vjik approved these changes

2024-10-27 14:36 UTC, merged

2024-10-27 14:37 UTC, vjik commented
@hacan359 Thank you 👍